# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: staging


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Python Package
        run: | 
          pip install mkdocs
          pip install mkdocs-material 
          pip install git+https://github.com/taivo/mkdocs-simple-tags.git
          pip install mkdocs-redirects
          pip install mkdocs-awesome-pages-plugin
          mkdocs gh-deploy --force
      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v1.1.0
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          dist_dir: site
